### ISSUE TITLE
Bug: Config value: 'markdown_extensions'. Error: Failed loading extension "mdx_truly_sane_lists".

### ISSUE THREAD

**Issue by nvuillam** [radude/mdx_truly_sane_lists#9]
Hi, on [MegaLinter](https://oxsecurity.github.io/megalinter/latest/) , to generate documentation, we use mike, mkdocs-material and mdx_truly_sane_lists as markdown extension.

It seems that since new [markdown PyPackage](https://github.com/Python-Markdown/markdown) version 3.4, mdx_truly_sane_lists does not succeed to be loaded anymore

`Config value: 'markdown_extensions'. Error: Failed loading extension "mdx_truly_sane_lists".`

It seems related to this breaking change -> https://python-markdown.github.io/change_log/release-3.4/#the-tables-extension-now-uses-a-style-attribute-instead-of-an-align-attribute-for-alignment

Error is visible in this job -> https://github.com/oxsecurity/megalinter/runs/7363159003?check_suite_focus=true

Maybe you could provide a patch ? :)

Thanks & best regards

**Comment by nvuillam** [comment]
Current workaround: force 3.3.7 version before installing mdx_truly_sane_lists

ex: `pip install --upgrade markdown==3.3.7 mdx_truly_sane_lists`

**Comment by xmatthias** [comment]
I think it's actually the removal of `markdown.version` [source](https://python-markdown.github.io/change_log/release-3.4/#previously-deprecated-objects-have-been-removed) which causes this, not the align attribute (at least at first glance, this extension doesn't contain the word "align" ...).

**Comment by relativisticelectron** [comment]
> I think it's actually the removal of `markdown.version` [source](https://python-markdown.github.io/change_log/release-3.4/#previously-deprecated-objects-have-been-removed) which causes this, not the align attribute (at least at first glance, this extension doesn't contain the word "align" ...).

Yes I can confirm that https://github.com/relativisticelectron/mdx_truly_sane_lists/commit/148d94fcf5c4e4c9d9b0a7cbd976a4f3107b9678  fixes the problem.

**Comment by radude** [comment]
Fixed by #10. I'll update the pip package in a few hours.

**Comment by relativisticelectron** [comment]
> Fixed by #10. I'll update the pip package in a few hours.

wonderful!

**Comment by nvuillam** [comment]
> Fixed by #10. I'll update the pip package in a few hours.

Thanks a lot :)
